---

    - name: Обновить список пакетов
      apt:
        update_cache: yes
      become: true
    - name: Установить Nginx, MySQL и PHP
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - mysql-server
        - php
        - php-fpm
        - php-mysql
      become: true

    - name: Копируем конфиг в nginx
      copy:
        src: files/default
        dest:  /etc/nginx/sites-available/default

    - name: Запустить сервисы
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - nginx
        - mysql
      become: true

    - name: Создание PHP файл с phpinfo()
      copy:
        dest: /var/www/html/phpinfo.php
        content: '<?php phpinfo(); ?>'
      become: true



    - name: Перезапустить Nginx
      systemd:
        name: nginx
        state: restarted
      become: true
